CREATE TABLE stocks
(
    id                                              INT PRIMARY KEY AUTO_INCREMENT COMMENT 'Unique identifier for each stock record',
    ticker                                          VARCHAR(255) COMMENT 'The stock symbol or ticker',
    stock_type                                      VARCHAR(255) COMMENT 'The type or category of the stock',
    stock_type_id                                   INT COMMENT 'The identifier for the stock type',
    sector_id                                       VARCHAR(255) COMMENT 'The sector in which the stock operates',
    CHECK (sector_id IN  ('technology', 'financial', 'healthcare', 'energy', 'consumerdefensive', 'consumercyclical', 'industrials','communicat ionservices', 'basicmaterials', 'utilities', 'realestate','communicationservices')),
    analyst_consensus                               VARCHAR(255) COMMENT 'Consensus rating by analysts for the stock (e.g., buy, sell, neutral)',
    CHECK (analyst_consensus IN ('buy', 'strongbuy', null, 'neutral', 'sell')),
    raw_consensus                                   VARCHAR(255) COMMENT 'Raw data or numerical representation of the consensus',
    buy_distribution                                FLOAT COMMENT 'Percentage of analysts recommending a buy',
    hold_distribution                               FLOAT COMMENT 'Percentage of analysts recommending to hold',
    sell_distribution                               FLOAT COMMENT 'Percentage of analysts recommending a sell',
    best_analyst_consensus                          VARCHAR(255) COMMENT 'Top analyst consensus rating for the stock',
    CHECK (best_analyst_consensus IN ('buy', 'strongbuy', null, 'neutral', 'sell')),
    best_analyst_raw_consensus                      VARCHAR(255) COMMENT 'Raw consensus of the top analyst',
    best_buy_distribution                           FLOAT COMMENT 'Percentage of top analysts recommending a buy',
    best_hold_distribution                          FLOAT COMMENT 'Percentage of top analysts recommending to hold',
    best_sell_distribution                          FLOAT COMMENT 'Percentage of top analysts recommending a sell',
    next_dividend_ex_date                           DATE COMMENT 'Date of the next dividend ex-date',
    next_dividend_pay_date                          DATE COMMENT 'Date of the next dividend payment',
    next_dividend_amount                            FLOAT COMMENT 'Amount of the next dividend',
    next_dividend_yield                             FLOAT COMMENT 'Yield of the next dividend',
    next_dividend_consensus                         VARCHAR(255) COMMENT 'Consensus on the next dividend',
    CHECK (next_dividend_consensus IN ('buy', 'strongbuy', null, 'neutral', 'sell')),
    next_dividend_bp_consensus                      VARCHAR(255) COMMENT 'Consensus in basis points for the next dividend',
    next_dividend_date_type                         VARCHAR(255) COMMENT 'Type of the next dividend date',
    next_dividend_price_target                      FLOAT COMMENT 'Price target based on the next dividend',
    next_dividend_num_buys                          INT COMMENT 'Number of buy recommendations based on next dividend',
    next_dividend_num_holds                         INT COMMENT 'Number of hold recommendations based on next dividend',
    next_dividend_num_sells                         INT COMMENT 'Number of sell recommendations based on next dividend',
    next_dividend_bp_price_target                   FLOAT COMMENT 'Price target in basis points for the next dividend',
    next_dividend_bp_num_buys                       INT COMMENT 'Number of buy recommendations in basis points for next dividend',
    next_dividend_bp_num_holds                      INT COMMENT 'Number of hold recommendations in basis points for next dividend',
    next_dividend_bp_num_sells                      INT COMMENT 'Number of sell recommendations in basis points for next dividend',
    next_dividend_rec_date                          DATE COMMENT 'Date of the next dividend record',
    next_dividend_eps                               FLOAT COMMENT 'Earnings per share for the next dividend',
    next_dividend_growth_since_date                 DATE COMMENT 'Date since the growth of the next dividend',
    next_dividend_sector_yield                      FLOAT COMMENT 'Yield of the sector for the next dividend',
    next_dividend_payout_ratio                      FLOAT COMMENT 'Payout ratio for the next dividend',
    next_dividend_annualized_payout                 FLOAT COMMENT 'Annualized payout for the next dividend',
    next_dividend_payout_interval                   VARCHAR(255) COMMENT 'Payout interval for the next dividend',
    next_dividend_announce_date                     DATE COMMENT 'Announcement date for the next dividend',
    next_dividend_is_special_dividend               BOOLEAN COMMENT 'Flag if the dividend is special',
    last_reported_eps_date                          DATE COMMENT 'Last date when EPS was reported',
    last_reported_eps_company                       VARCHAR(255) COMMENT 'Company for which the last EPS was reported',
    last_reported_eps_ticker                        VARCHAR(255) COMMENT 'Ticker for which the last EPS was reported',
    last_reported_eps_period_ending                 DATE COMMENT 'Period ending date for the last reported EPS',
    last_reported_eps                               FLOAT COMMENT 'Last reported earnings per share',
    reported_eps                                    FLOAT COMMENT 'Reported earnings per share',
    last_eps                                        FLOAT COMMENT 'Last earnings per share',
    market_cap                                      FLOAT COMMENT 'Market capitalization of the stock',
    market_cap_currency_id                          INT COMMENT 'Currency ID for the market capitalization',
    sector                                          VARCHAR(255) COMMENT 'Sector of the stock',
    stock_id                                        INT COMMENT 'Unique ID for the stock',
    surprise                                        FLOAT COMMENT 'Surprise factor for the stock based on expectations',
    time_of_day                                     VARCHAR(255) COMMENT 'Time of day for the stock data record',
    is_confirmed                                    BOOLEAN COMMENT 'Flag indicating if the data is confirmed',
    currency_type_id                                INT COMMENT 'ID for the type of currency',
    eps_currency_type_id                            INT COMMENT 'ID for the currency type of EPS',
    fiscal_period                                   VARCHAR(255) COMMENT 'Fiscal period for the stock',
    fiscal_year                                     INT COMMENT 'Fiscal year for the stock',
    fiscal_quarter_ending_date                      DATE COMMENT 'Date when the fiscal quarter ends',
    total_income                                    FLOAT COMMENT 'Total income for the stock',
    total_revenue                                   FLOAT COMMENT 'Total revenue for the stock',
    revenue_income_currency_id                      INT COMMENT 'Currency ID for the revenue and income',
    revenue_per_share                               FLOAT COMMENT 'Revenue per share for the stock',
    revenue_per_share_currency_id                   INT COMMENT 'Currency ID for the revenue per share',
    p_e_ratio                                       FLOAT COMMENT 'Price to earnings ratio for the stock',
    p_e_ratio_date                                  DATE COMMENT 'Date for the P/E ratio data',
    net_income                                      FLOAT COMMENT 'Net income for the stock',
    net_income_currency_id                          INT COMMENT 'Currency ID for the net income',
    income_per_share                                FLOAT COMMENT 'Income per share for the stock',
    income_per_share_currency_id                    INT COMMENT 'Currency ID for the income per share',
    is_surprise                                     BOOLEAN COMMENT 'Flag indicating if the stock was a surprise',
    is_surprise_percent                             FLOAT COMMENT 'Percentage surprise of the stock',
    last_reported_eps_fiscal_period                 VARCHAR(255) COMMENT 'Last reported EPS fiscal period',
    last_reported_eps_fiscal_year                   INT COMMENT 'Last reported EPS fiscal year',
    last_reported_eps_fiscal_quarter_ending_date    DATE COMMENT 'Last reported EPS fiscal quarter ending date',
    last_reported_eps_currency_type_id              INT COMMENT 'Last reported EPS currency type ID',
    last_reported_eps_announce_date                 DATE COMMENT 'Announcement date of the last reported EPS',
    last_reported_eps_announce_time_of_day          VARCHAR(255) COMMENT 'Announcement time of the last reported EPS',
    last_reported_eps_is_confirmed                  BOOLEAN COMMENT 'Flag indicating if the last reported EPS is confirmed',
    last_reported_eps_reported_eps                  FLOAT COMMENT 'Last reported EPS value',
    last_reported_eps_surprise                      FLOAT COMMENT 'Surprise factor of the last reported EPS',
    last_reported_eps_is_surprise                   BOOLEAN COMMENT 'Flag indicating if the last reported EPS was a surprise',
    last_reported_eps_is_surprise_percent           FLOAT COMMENT 'Percentage surprise of the last reported EPS',
    last_reported_eps_guidance                      FLOAT COMMENT 'Guidance value of the last reported EPS',
    last_reported_eps_is_revised                    BOOLEAN COMMENT 'Flag indicating if the last reported EPS was revised',
    last_reported_eps_is_revised_up                 BOOLEAN COMMENT 'Flag indicating if the last reported EPS was revised up',
    last_reported_eps_is_revised_down               BOOLEAN COMMENT 'Flag indicating if the last reported EPS was revised down',
    last_reported_eps_num_upgrades                  INT COMMENT 'Number of upgrades based on the last reported EPS',
    last_reported_eps_num_downgrades                INT COMMENT 'Number of downgrades based on the last reported EPS',
    last_reported_eps_num_revisions                 INT COMMENT 'Number of revisions for the last reported EPS',
    last_reported_eps_num_revisions_up              INT COMMENT 'Number of upward revisions for the last reported EPS',
    last_reported_eps_num_revisions_down            INT COMMENT 'Number of downward revisions for the last reported EPS',
    last_reported_eps_num_analysts                  INT COMMENT 'Number of analysts for the last reported EPS',
    last_reported_eps_num_buys                      INT COMMENT 'Number of buy recommendations for the last reported EPS',
    last_reported_eps_num_holds                     INT COMMENT 'Number of hold recommendations for the last reported EPS',
    last_reported_eps_num_sells                     INT COMMENT 'Number of sell recommendations for the last reported EPS',
    last_reported_eps_num_strong_buys               INT COMMENT 'Number of strong buy recommendations for the last reported EPS',
    last_reported_eps_num_strong_sells              INT COMMENT 'Number of strong sell recommendations for the last reported EPS',
    last_reported_eps_sector_average                FLOAT COMMENT 'Sector average for the last reported EPS',
    last_reported_eps_price_target                  FLOAT COMMENT 'Price target based on the last reported EPS',
    last_reported_eps_price_target_high             FLOAT COMMENT 'Highest price target based on the last reported EPS',
    last_reported_eps_price_target_low              FLOAT COMMENT 'Lowest price target based on the last reported EPS',
    last_reported_eps_price_target_average          FLOAT COMMENT 'Average price target based on the last reported EPS',
    last_reported_eps_revenue_estimate              FLOAT COMMENT 'Revenue estimate based on the last reported EPS',
    last_reported_eps_revenue_estimate_high         FLOAT COMMENT 'Highest revenue estimate based on the last reported EPS',
    last_reported_eps_revenue_estimate_low          FLOAT COMMENT 'Lowest revenue estimate based on the last reported EPS',
    last_reported_eps_revenue_estimate_average      FLOAT COMMENT 'Average revenue estimate based on the last reported EPS',
    last_reported_eps_earnings_estimate             FLOAT COMMENT 'Earnings estimate based on the last reported EPS',
    last_reported_eps_earnings_estimate_high        FLOAT COMMENT 'Highest earnings estimate based on the last reported EPS',
    last_reported_eps_earnings_estimate_low         FLOAT COMMENT 'Lowest earnings estimate based on the last reported EPS',
    last_reported_eps_earnings_estimate_average     FLOAT COMMENT 'Average earnings estimate based on the last reported EPS',
    last_reported_eps_num_analysts_estimates        INT COMMENT 'Number of analysts estimates for the last reported EPS',
    last_reported_eps_num_buys_estimates            INT COMMENT 'Number of buy estimates for the last reported EPS',
    last_reported_eps_num_holds_estimates           INT COMMENT 'Number of hold estimates for the last reported EPS',
    last_reported_eps_num_sells_estimates           INT COMMENT 'Number of sell estimates for the last reported EPS',
    last_reported_eps_num_strong_buys_estimates     INT COMMENT 'Number of strong buy estimates for the last reported EPS',
    last_reported_eps_num_strong_sells_estimates    INT COMMENT 'Number of strong sell estimates for the last reported EPS',
    last_reported_eps_guidance_revenue              FLOAT COMMENT 'Revenue guidance for the last reported EPS',
    last_reported_eps_guidance_revenue_high         FLOAT COMMENT 'Highest revenue guidance for the last reported EPS',
    last_reported_eps_guidance_revenue_low          FLOAT COMMENT 'Lowest revenue guidance for the last reported EPS',
    last_reported_eps_guidance_revenue_average      FLOAT COMMENT 'Average revenue guidance for the last reported EPS',
    last_reported_eps_guidance_earnings             FLOAT COMMENT 'Earnings guidance for the last reported EPS',
    last_reported_eps_guidance_earnings_high        FLOAT COMMENT 'Highest earnings guidance for the last reported EPS',
    last_reported_eps_guidance_earnings_low         FLOAT COMMENT 'Lowest earnings guidance for the last reported EPS',
    last_reported_eps_guidance_earnings_average     FLOAT COMMENT 'Average earnings guidance for the last reported EPS',
    last_reported_eps_guidance_num_analysts         INT COMMENT 'Number of analysts for the guidance of the last reported EPS',
    last_reported_eps_guidance_num_buys             INT COMMENT 'Number of buy recommendations for the guidance of the last reported EPS',
    last_reported_eps_guidance_num_holds            INT COMMENT 'Number of hold recommendations for the guidance of the last reported EPS',
    last_reported_eps_guidance_num_sells            INT COMMENT 'Number of sell recommendations for the guidance of the last reported EPS',
    last_reported_eps_guidance_num_strong_buys      INT COMMENT 'Number of strong buy recommendations for the guidance of the last reported EPS',
    last_reported_eps_guidance_num_strong_sells     INT COMMENT 'Number of strong sell recommendations for the guidance of the last reported EPS',
    last_reported_eps_guidance_price_target         FLOAT COMMENT 'Price target based on the guidance of the last reported EPS',
    last_reported_eps_guidance_price_target_high    FLOAT COMMENT 'Highest price target based on the guidance of the last reported EPS',
    last_reported_eps_guidance_price_target_low     FLOAT COMMENT 'Lowest price target based on the guidance of the last reported EPS',
    last_reported_eps_guidance_price_target_average FLOAT COMMENT 'Average price target based on the guidance of the last reported EPS',
    next_eps_announce_date                          DATE COMMENT 'Announcement date for the next EPS',
    next_eps_announce_time_of_day                   VARCHAR(255) COMMENT 'Announcement time for the next EPS',
    next_eps_is_confirmed                           BOOLEAN COMMENT 'Flag indicating if the next EPS is confirmed',
    next_eps_estimated_eps                          FLOAT COMMENT 'Estimated EPS value for the next announcement',
    next_eps_surprise                               FLOAT COMMENT 'Surprise factor for the next EPS',
    next_eps_is_surprise                            BOOLEAN COMMENT 'Flag indicating if the next EPS will be a surprise',
    next_eps_is_surprise_percent                    FLOAT COMMENT 'Percentage surprise for the next EPS',
    next_eps_is_revised                             BOOLEAN COMMENT 'Flag indicating if the next EPS is revised',
    next_eps_is_revised_up                          BOOLEAN COMMENT 'Flag indicating if the next EPS is revised up',
    next_eps_is_revised_down                        BOOLEAN COMMENT 'Flag indicating if the next EPS is revised down',
    next_eps_num_upgrades                           INT COMMENT 'Number of upgrades based on the next EPS',
    next_eps_num_downgrades                         INT COMMENT 'Number of downgrades based on the next EPS',
    next_eps_num_revisions                          INT COMMENT 'Number of revisions for the next EPS',
    next_eps_num_revisions_up                       INT COMMENT 'Number of upward revisions for the next EPS',
    next_eps_num_revisions_down                     INT COMMENT 'Number of downward revisions for the next EPS',
    next_eps_num_analysts                           INT COMMENT 'Number of analysts for the next EPS',
    next_eps_num_buys                               INT COMMENT 'Number of buy recommendations for the next EPS',
    next_eps_num_holds                              INT COMMENT 'Number of hold recommendations for the next EPS',
    next_eps_num_sells                              INT COMMENT 'Number of sell recommendations for the next EPS',
    next_eps_num_strong_buys                        INT COMMENT 'Number of strong buy recommendations for the next EPS',
    next_eps_num_strong_sells                       INT COMMENT 'Number of strong sell recommendations for the next EPS',
    next_eps_sector_average                         FLOAT COMMENT 'Sector average for the next EPS',
    next_eps_price_target                           FLOAT COMMENT 'Price target based on the next EPS',
    next_eps_price_target_high                      FLOAT COMMENT 'Highest price target based on the next EPS',
    next_eps_price_target_low                       FLOAT COMMENT 'Lowest price target based on the next EPS',
    next_eps_price_target_average                   FLOAT COMMENT 'Average price target based on the next EPS',
    next_eps_revenue_estimate                       FLOAT COMMENT 'Revenue estimate for the next EPS',
    next_eps_revenue_estimate_high                  FLOAT COMMENT 'Highest revenue estimate for the next EPS',
    next_eps_revenue_estimate_low                   FLOAT COMMENT 'Lowest revenue estimate for the next EPS',
    next_eps_revenue_estimate_average               FLOAT COMMENT 'Average revenue estimate for the next EPS',
    next_eps_earnings_estimate                      FLOAT COMMENT 'Earnings estimate for the next EPS',
    next_eps_earnings_estimate_high                 FLOAT COMMENT 'Highest earnings estimate for the next EPS',
    next_eps_earnings_estimate_low                  FLOAT COMMENT 'Lowest earnings estimate for the next EPS',
    next_eps_earnings_estimate_average              FLOAT COMMENT 'Average earnings estimate for the next EPS',
    next_eps_num_analysts_estimates                 INT COMMENT 'Number of analysts estimates for the next EPS',
    next_eps_num_buys_estimates                     INT COMMENT 'Number of buy estimates for the next EPS',
    next_eps_num_holds_estimates                    INT COMMENT 'Number of hold estimates for the next EPS',
    next_eps_num_sells_estimates                    INT COMMENT 'Number of sell estimates for the next EPS',
    next_eps_num_strong_buys_estimates              INT COMMENT 'Number of strong buy estimates for the next EPS',
    next_eps_num_strong_sells_estimates             INT COMMENT 'Number of strong sell estimates for the next EPS',
    next_eps_guidance_revenue                       FLOAT COMMENT 'Revenue guidance for the next EPS',
    next_eps_guidance_revenue_high                  FLOAT COMMENT 'Highest revenue guidance for the next EPS',
    next_eps_guidance_revenue_low                   FLOAT COMMENT 'Lowest revenue guidance for the next EPS',
    next_eps_guidance_revenue_average               FLOAT COMMENT 'Average revenue guidance for the next EPS',
    next_eps_guidance_earnings                      FLOAT COMMENT 'Earnings guidance for the next EPS',
    next_eps_guidance_earnings_high                 FLOAT COMMENT 'Highest earnings guidance for the next EPS',
    next_eps_guidance_earnings_low                  FLOAT COMMENT 'Lowest earnings guidance for the next EPS',
    next_eps_guidance_earnings_average              FLOAT COMMENT 'Average earnings guidance for the next EPS',
    next_eps_guidance_num_analysts                  INT COMMENT 'Number of analysts for the guidance of the next EPS',
    next_eps_guidance_num_buys                      INT COMMENT 'Number of buy recommendations for the guidance of the next EPS',
    next_eps_guidance_num_holds                     INT COMMENT 'Number of hold recommendations for the guidance of the next EPS',
    next_eps_guidance_num_sells                     INT COMMENT 'Number of sell recommendations for the guidance of the next EPS',
    next_eps_guidance_num_strong_buys               INT COMMENT 'Number of strong buy recommendations for the guidance of the next EPS',
    next_eps_guidance_num_strong_sells              INT COMMENT 'Number of strong sell recommendations for the guidance of the next EPS',
    next_eps_guidance_price_target                  FLOAT COMMENT 'Price target based on the guidance of the next EPS',
    next_eps_guidance_price_target_high             FLOAT COMMENT 'Highest price target based on the guidance of the next EPS',
    next_eps_guidance_price_target_low              FLOAT COMMENT 'Lowest price target based on the guidance of the next EPS',
    next_eps_guidance_price_target_average          FLOAT COMMENT 'Average price target based on the guidance of the next EPS',
    is_next_eps_guidance_available                  BOOLEAN COMMENT 'Flag indicating if guidance is available for the next EPS',
    created_at                                      TIMESTAMP COMMENT 'Timestamp of the creation of the record',
    updated_at                                      TIMESTAMP COMMENT 'Timestamp of the last update of the record',
    next_earning_date                               DATE COMMENT 'Next anticipated earning date',
    next_earning_announce_date                      DATE COMMENT 'Date of next earning announcement',
    next_earning_announce_time_of_day               VARCHAR(255) COMMENT 'Time of next earning announcement',
    next_earning_is_confirmed                       BOOLEAN COMMENT 'Flag if the next earning date is confirmed',
    next_earning_period_ending                      DATE COMMENT 'Ending date of the next earning period',
    next_earning_stock_id                           INT COMMENT 'Stock ID associated with the next earning',
    next_earning_ticker                             VARCHAR(255) COMMENT 'Ticker for the next earning',
    last_trade_price                                FLOAT COMMENT 'Price of the last trade',
    last_trade_time_of_day                          VARCHAR(255) COMMENT 'Time of the last trade',
    last_trade_date                                 DATE COMMENT 'Date of the last trade',
    last_trade_stock_id                             INT COMMENT 'Stock ID for the last trade',
    last_trade_ticker                               VARCHAR(255) COMMENT 'Ticker for the last trade',
    last_trade_price_type_id                        INT COMMENT 'Type ID for the last trade price',
    last_trade_currency_type_id                     INT COMMENT 'Currency Type ID for the last trade',
    stock_price_change                              FLOAT COMMENT 'Change in stock price',
    stock_price_change_currency_type_id             INT COMMENT 'Currency type ID for stock price change',
    stock_price_change_date                         DATE COMMENT 'Date of the stock price change',
    stock_price_change_time_of_day                  VARCHAR(255) COMMENT 'Time of the stock price change',
    stock_price_change_stock_id                     INT COMMENT 'Stock ID for the price change',
    stock_price_change_ticker                       VARCHAR(255) COMMENT 'Ticker for the price change',
    stock_price_change_type_id                      INT COMMENT 'Type ID for the stock price change',
    current_price                                   FLOAT COMMENT 'Current price of the stock',
    current_price_time_of_day                       VARCHAR(255) COMMENT 'Time for the current price',
    current_price_date                              DATE COMMENT 'Date of the current price',
    current_price_stock_id                          INT COMMENT 'Stock ID for the current price',
    current_price_ticker                            VARCHAR(255) COMMENT 'Ticker for the current price',
    current_price_type_id                           INT COMMENT 'Type ID for the current price',
    current_price_currency_type_id                  INT COMMENT 'Currency Type ID for the current price',
    current_price_change                            FLOAT COMMENT 'Change in current price',
    current_price_change_percent                    FLOAT COMMENT 'Percentage change in current price',
    current_price_last_reported_eps                 FLOAT COMMENT 'Last reported EPS for the current price',
    current_price_next_earning_date                 DATE COMMENT 'Next earning date for the current price',
    current_price_next_dividend_date                DATE COMMENT 'Next dividend date for the current price',
    current_price_stock_type                        VARCHAR(255) COMMENT 'Stock type for the current price',
    current_price_stock_type_id                     INT COMMENT 'Stock type ID for the current price',
    current_price_sector_id                         INT COMMENT 'Sector ID for the current price',
    current_price_last_trade_price                  FLOAT COMMENT 'Last trade price for the current price',
    current_price_last_trade_time_of_day            VARCHAR(255) COMMENT 'Last trade time for the current price',
    current_price_last_trade_date                   DATE COMMENT 'Last trade date for the current price',
    current_price_stock_price_change                FLOAT COMMENT 'Stock price change for the current price',
    current_price_stock_price_change_percent        FLOAT COMMENT 'Stock price change percentage for the current price',
    current_price_stock_price_change_date           DATE COMMENT 'Stock price change date for the current price',
    current_price_stock_price_change_time_of_day    VARCHAR(255) COMMENT 'Stock price change time for the current price',
    current_price_stock_price_change_stock_id       INT COMMENT 'Stock ID for the price change for the current price',
    current_price_stock_price_change_ticker         VARCHAR(255) COMMENT 'Ticker for the price change for the current price',
    current_price_stock_price_change_type_id        INT COMMENT 'Type ID for the price change for the current price',
    analyst_consensus_distribution_buy              FLOAT COMMENT 'Analyst consensus for buying distribution',
    analyst_consensus_distribution_hold             FLOAT COMMENT 'Analyst consensus for holding distribution',
    analyst_consensus_distribution_sell             FLOAT COMMENT 'Analyst consensus for selling distribution',
    best_analyst_consensus_distribution_buy         FLOAT COMMENT 'Best analyst consensus for buying distribution',
    best_analyst_consensus_distribution_hold        FLOAT COMMENT 'Best analyst consensus for holding distribution',
    best_analyst_consensus_distribution_sell        FLOAT COMMENT 'Best analyst consensus for selling distribution',
    next_dividend_date_ticker                       VARCHAR(255) COMMENT 'Ticker for the next dividend date',
    next_dividend_date_company                      VARCHAR(255) COMMENT 'Company for the next dividend date',
    next_dividend_date_market_cap                   BIGINT COMMENT 'Market cap for the next dividend date',
    next_dividend_date_market_cap_currency_id       INT COMMENT 'Currency ID for market cap at the next dividend date',
    next_dividend_date_sector                       INT COMMENT 'Sector for the next dividend date',
    next_dividend_date_stock_id                     INT COMMENT 'Stock ID for the next dividend date',
    next_dividend_date_stock_type_id                INT COMMENT 'Stock type ID for the next dividend date',
    next_dividend_date_currency_type_id             INT COMMENT 'Currency Type ID for the next dividend date',
    next_earnings_report_url_report                 TEXT COMMENT 'URL for the next earnings report',
    price_target                                    FLOAT COMMENT 'Target price for the stock',
    hedge_fund_sentiment_data_rating                INT COMMENT 'Rating based on hedge fund sentiment',
    hedge_fund_sentiment_data_score                 FLOAT COMMENT 'Score based on hedge fund sentiment',
    insider_sentiment_data_rating                   INT COMMENT 'Rating based on insider sentiment',
    insider_sentiment_data_stock_score              FLOAT COMMENT 'Stock score based on insider sentiment',
    blogger_sentiment_data_rating_if_exists         INT COMMENT 'Blogger sentiment rating if it exists',
    blogger_sentiment_data_rating                   INT COMMENT 'Blogger sentiment rating',
    blogger_sentiment_data_bearish_count            INT COMMENT 'Count of bearish sentiments from bloggers',
    blogger_sentiment_data_bullish_count            INT COMMENT 'Count of bullish sentiments from bloggers',
    landmark_prices_year_to_date_date               DATE COMMENT 'Year-to-date landmark price date',
    landmark_prices_year_to_date_d                  VARCHAR(255) COMMENT 'Descriptor for year-to-date landmark prices',
    landmark_prices_year_to_date_p                  FLOAT COMMENT 'Year-to-date landmark price',
    landmark_prices_three_months_ago_date           DATE COMMENT 'Date for landmark price three months ago',
    landmark_prices_three_months_ago_d              VARCHAR(255) COMMENT 'Descriptor for landmark prices three months ago',
    landmark_prices_three_months_ago_p              FLOAT COMMENT 'Landmark price from three months ago',
    landmark_prices_year_ago_date                   DATE COMMENT 'Date for landmark price a year ago',
    landmark_prices_year_ago_d                      VARCHAR(255) COMMENT 'Descriptor for landmark prices a year ago',
    landmark_prices_year_ago_p                      FLOAT COMMENT 'Landmark price from a year ago',
    company_name                                    VARCHAR(255) COMMENT 'Name of the company',
    best_price_target                               FLOAT COMMENT 'Highest price target',
    dividend                                        FLOAT COMMENT 'Dividend amount',
    dividend_yield                                  FLOAT COMMENT 'Dividend yield percentage',
    pe_ratio                                        FLOAT COMMENT 'Price to Earnings ratio',
    high_52_weeks                                   FLOAT COMMENT 'Highest price in the past 52 weeks',
    low_52_weeks                                    FLOAT COMMENT 'Lowest price in the past 52 weeks',
    hedge_fund_sentiment_rating                     INT COMMENT 'Hedge fund sentiment rating',
    hedge_fund_sentiment_score                      FLOAT COMMENT 'Score based on hedge fund sentiment',
    insider_sentiment_rating                        INT COMMENT 'Insider sentiment rating',
    insider_stock_score                             FLOAT COMMENT 'Score based on insider sentiment',
    blogger_sentiment_rating_if_exists              INT COMMENT 'Blogger sentiment rating if exists',
    blogger_sentiment_rating                        INT COMMENT 'Blogger sentiment rating',
    blogger_bearish_count                           INT COMMENT 'Count of bearish sentiments from bloggers',
    blogger_bullish_count                           INT COMMENT 'Count of bullish sentiments from bloggers',
    next_earnings_report_date                       DATE COMMENT 'Date of the next earnings report',
    stock_uid                                       VARCHAR(255) COMMENT 'Unique identifier for the stock',
    smart_score                                     FLOAT COMMENT 'Smart score for stock evaluation',
    next_dividend_date_consensus                    VARCHAR(255) COMMENT 'Consensus for the next dividend date',
    should_add_link_to_stock_page                   BOOLEAN COMMENT 'Flag to determine if a link should be added to the stock page',
    expense_ratio                                   FLOAT COMMENT 'Expense ratio for the stock or ETF',
    news_sentiment                                  INT COMMENT 'Sentiment score based on news articles',
    year_to_date_landmark_date                      DATE COMMENT 'Year-to-date reference date for landmark price',
    year_to_date_landmark_price                     FLOAT COMMENT 'Landmark price for the current year up to date',
    three_months_ago_landmark_date                  DATE COMMENT 'Reference date for landmark price three months ago',
    three_months_ago_landmark_price                 FLOAT COMMENT 'Landmark price from three months ago',
    year_ago_landmark_date                          DATE COMMENT 'Reference date for landmark price a year ago',
    year_ago_landmark_price                         FLOAT COMMENT 'Landmark price from a year ago',
    price_target_currency_id                        INT COMMENT 'Currency ID for the target price',
    market_country_id                               INT COMMENT 'Country ID associated with the stock market',
    company_full_name                               VARCHAR(255) COMMENT 'Full name of the company',
    next_dividend_market_cap                        FLOAT COMMENT 'Market cap value for the next dividend date',
    next_dividend_sector                            INT COMMENT 'Sector ID for the next dividend date',
    last_reported_eps_url_report                    TEXT COMMENT 'URL link to the last reported EPS report',
    last_reported_eps_low_estimate                  FLOAT COMMENT 'Lowest estimate for the last reported EPS',
    last_reported_eps_high_estimate                 FLOAT COMMENT 'Highest estimate for the last reported EPS',
    last_reported_eps_sales_estimate                FLOAT COMMENT 'Sales estimate for the last reported EPS',
    last_reported_eps_sales_low_estimate            FLOAT COMMENT 'Lowest sales estimate for the last reported EPS',
    last_reported_eps_sales_high_estimate           FLOAT COMMENT 'Highest sales estimate for the last reported EPS',
    last_reported_eps_smart_score                   FLOAT COMMENT 'Smart score based on the last reported EPS',
    next_earning_eps                                FLOAT COMMENT 'EPS estimate for the next earning period',
    next_earning_reported_eps                       FLOAT COMMENT 'Reported EPS for the next earning',
    next_earning_market_cap                         FLOAT COMMENT 'Market cap value for the next earning date',
    next_earning_sector                             INT COMMENT 'Sector ID for the next earning date',
    next_earning_surprise                           FLOAT COMMENT 'Surprise value for the next earning',
    next_earning_url_report                         VARCHAR(255) COMMENT 'URL link to the next earnings report',
    next_earning_low_estimate                       FLOAT COMMENT 'Lowest EPS estimate for the next earning',
    next_earning_high_estimate                      FLOAT COMMENT 'Highest EPS estimate for the next earning',
    next_earning_sales_estimate                     FLOAT COMMENT 'Sales estimate for the next earning',
    next_earning_sales_low_estimate                 FLOAT COMMENT 'Lowest sales estimate for the next earning',
    next_earning_sales_high_estimate                FLOAT COMMENT 'Highest sales estimate for the next earning',
    next_earning_smart_score                        FLOAT COMMENT 'Smart score based on the next earning'
);
