name: Deploy bot

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGION: us-east-1
  STAGE: stage
  FIRST_SETUP: false

jobs:

  deployBot:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' -x "node_modules/*" -x "deploy.sh"> /dev/null

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: chgpt3
          environment_name: Chgpt3-env-1
          wait_for_environment_recovery: 60
          version_label: ${{ github.run_id }}
          region: ${{ env.REGION }}
          deployment_package: deploy.zip


